### ISSUE TITLE
invalid code example at README.md - addr: Int64;  

### ISSUE THREAD

**Issue by skalogryz** [stievie/TCapstone#1]
addr variable cannot be of type Int64

the first parameter of disasm.GetNext() is var of **UInt64** 

compiling the sample code returns with an error:
Error: Call by var for arg no. 1 has to match exactly: Got "Int64" expected "QWord"

**Comment by stievie** [comment]
What compiler are you using? The `addr` variable is a UInt64 which should be a QWord in `test.dpr` line 13.

**Comment by skalogryz** [comment]
it's not in the actual code.

the problem is with README.md file.
The code-snippet there shows addr: Int64;

**Comment by stievie** [comment]
Ah okay, thankk you I'll fix it.
